disabled_rules:
  - closure_parameter_position
  - weak_delegate
  - identifier_name
  - force_cast
  - file_length
  - type_body_length
  - switch_case_alignment
  - large_tuple

opt_in_rules:
  - indentation_width 

indentation_width:
  severity: warning
  indentation_width: 4
  include_comments: true
