name: Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Swift
        uses: swift-actions/setup-swift@v2

      - name: Install dependencies
        run: brew install swiftlint || echo "SwiftLint already installed"

      - name: Run SwiftLint
        run: swift tasks.swift lint
