name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Swift
        uses: swift-actions/setup-swift@v2

      - name: Test PDKit
        run: swift tasks.swift test pdkit

      - name: Test PatchData
        run: swift tasks.swift test patchdata

      - name: Test PatchDay
        run: swift tasks.swift test patchday
